### PR TITLE
add ice servers to connection options

### PR DESCRIPTION
**Pull request by OlliePugh**
Add the ability to specify ice servers on connection.

Also supressed all of the TypeScript errors with `@ts-ignore`'s but also corrected some types.

Also removed some blue bird dependencies. 

This is a lot of little bits I spotted along the way. If you're not happy with all the changes I can take out the typescript changes and bluebird just to get the ice stuff merged.

### CODE REVIEW

**Review by smyrgeorge — APPROVED** [review]
Thanks for your work!
It looks ok!

**Comment by smyrgeorge** [comment]
The build fails. I think the build process is a bit outdated.

**Comment by OlliePugh** [comment]
> The build fails. I think the build process is a bit outdated. 

Cool I'll take a look at it today

**Comment by OlliePugh** [comment]
I also realised that I added some unit tests I was working on. Do we even want unit tests? this needs integration tests more than anything really.

**Comment by OlliePugh** [comment]
So, just pushed a fix to the pipeline (I think) but, the package is over the 10kb threshold that was set for size-limit.

0.3.2 is also 39kb so its been over 10kb for a while.

Also I started adding unit tests but I'm not sure if we should keep them in this as they don't really test anything.

**Comment by OlliePugh** [comment]
Just need an approval on the update to the workflow then I think its good to go

**Comment by smyrgeorge** [comment]
I just merged it. I will deploy also deploy the latest version to `npmjs`.

**Comment by smyrgeorge** [comment]
I just published the `0.3.3` version to `npmjs`.

**Comment by OlliePugh** [comment]
Great thanks

**Pull request merged**
